# Generated by Django 5.0.4 on 2024-05-13 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_product_sub_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sub_category',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_sub': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_products', to='app.category'),
        ),
    ]
